import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MeetStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <ClerkProvider
        appearance={{
          variables: {
            colorPrimary: "#0E78F9",
            colorForeground: "#ffffff",
            colorBackground: "#1c1f2e",
            colorInput: "#252a41",
            colorInputForeground: "#ffffff",
          },
          elements: {
            badge: {
              color: "#9CA3AF", // Light gray
            },

            badgePrimary: {
              color: "#9CA3AF",
            },

            menuButton: {
              color: "#FFFFFF",
            },

            menuButtonIcon: {
              color: "#FFFFFF",
            },

            socialButtonsBlockButton: {
              backgroundColor: "#252A41",
              border: "1px solid #3A3F5A",
              color: "#FFFFFF",
              borderRadius: "12px",
            },
            userButtonPopoverCard: {
              backgroundColor: "#FFFFFF",
            },

            userButtonPopoverActionButton: {
              color: "#FFFFFF",
              "&:hover": {
                backgroundColor: "#252A41",
                color: "#FFFFFF",
              },
            },

            userButtonPopoverActionButtonText: {
              color: "#FFFFFF",
            },

            userButtonPopoverFooter: {
              backgroundColor: "#1C1F2E",
            },
          },
        }}
      >
        <body className="min-h-full flex flex-col bg-dark-2 text-white">
          {children}
          <Toaster/>
        </body>
      </ClerkProvider>
    </html>
  );
}
